/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cpp_core_TunersNativeTest */

#ifndef _Included_cpp_core_TunersNativeTest
#define _Included_cpp_core_TunersNativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cpp_core_TunersNativeTest
 * Method:    nativeTestScanErrorFindingDevices
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_cpp_core_TunersNativeTest_nativeTestScanErrorFindingDevices
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
